name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      # Clerk Authentication
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      NEXT_PUBLIC_CLERK_SIGN_IN_URL: '/sign-in'
      NEXT_PUBLIC_CLERK_SIGN_UP_URL: '/sign-up'
      NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: '/game'
      NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: '/game'

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run type check
      run: npm run type-check
      
    - name: Run linter
      run: npm run lint || exit 0
      
    - name: Build
      run: npm run build 